### ISSUE TITLE
Link to the user manual is not working.

### ISSUE THREAD

**Issue by timKraeuter** [nl-utwente-groove/nl-utwente-groove.github.io#1]
Good job moving Groove from SVN to Git and with the new website!

Unfortunately, the link to the user manual provided [here](https://groove.cs.utwente.nl/manual.html) does not work. The same is true for the quick manual.
It leads to [https://groove.cs.utwente.nl/usermanual/blob/master/usermanual.pdf](https://groove.cs.utwente.nl/usermanual/blob/master/usermanual.pdf), but no **usermanual.pdf** exists in the root of this repository.

Maybe change the link to point to your user manual repository (if the user manual is frequently updated there).
[https://github.com/nl-utwente-groove/usermanual/blob/master/usermanual.pdf](https://github.com/nl-utwente-groove/usermanual/blob/master/usermanual.pdf)

Or maybe a raw link just to the file:
[https://raw.githubusercontent.com/nl-utwente-groove/usermanual/master/usermanual.pdf](https://raw.githubusercontent.com/nl-utwente-groove/usermanual/master/usermanual.pdf)

**Comment by rensink** [comment]
Thanks for reporting this; should be repaired now
