### ISSUE TITLE
Real values matched in scientific notation

### ISSUE THREAD

**Issue by LanternCode** [nl-utwente-groove/nl-utwente-groove.github.io#2]
I made a node in the start graph with a very very small real value used for its only attribute. When the node is matched, it is matched using the scientific notation, which no longer matches the real type specified in the type graph. This is problematic as it means our rules can match (and create) nodes that defy the type graph. While such nodes are still “consumed” as expected, we are worried this could have side effects. This is in Groove 6.8.1. I attached a grammar replicating this issue. 
[realsbugreport.gps.zip](https://github.com/user-attachments/files/15954137/realsbugreport.gps.zip)

**Comment by rensink** [comment]
Thanks for reporting this. It's been resolved in the source code and will be part of the next release.
