### ISSUE TITLE
Groove crashes in a failed call to an external function

### ISSUE THREAD

**Issue by LanternCode** [nl-utwente-groove/nl-utwente-groove.github.io#3]
In one of my grammars, once I deleted a node in the type graph and saved it, Groove crashed. Trying to open the grammar then immediately crashes with the same error message (trace attached). I opened Groove without the classpath to see if that would at least let me launch it, and it did. I attached the “errors in grammar” part to the trace. For some reason, although the class worked previously (and was not modified between runs), something causes a crash when loading. I deleted the leftovers of the removed type of the node in that grammar and saved it, after which opened it with the classpath with success. It seems that including a non-existing type in a call to the external function, instead of throwing an error, just crashes Groove immediately.

This report is trickier, definitely not something I'd be trying to replicate, but maybe the stack trace points somewhere.

Operation: Deleted a node from the type graph and pressed Save
Errors in Groove:
Error in rule 'message': Can't parse m_passed = message(vn.sentiment, l.str): Unparsed suffix: (vn.sentiment, l.str) in 'let:m_passed = message(vn.sentiment, l.str)'
Error in rule 'update': Can't parse sentiment = update(sum(m.m_passed)/toReal(sum(m.count)), p.nAggW, v1.sentiment, v1.sAggW): Unparsed suffix: (sum(m.m_passed)/toReal(sum(m.count)), p.nAggW, v1.sentiment, v1.sAggW) in 'let:sentiment = update(sum(m.m_passed)/toReal(sum(m.count)), p.nAggW, v1.sentiment, v1.sAggW)'
Error in property key 'User operations': Class 'MyMPNN' cannot be loaded
Unknown node type 'type:Params'

Stack Trace:
[Groove Crash.txt](https://github.com/user-attachments/files/15954195/Groove.Crash.txt)

The grammar is not attached as it was updated several times since then and the issue was resolved. Hopefully the description is good enough :)

**Comment by rensink** [comment]
Thanks for reporting this. This seems to be independent of the user operations - I was able to reproduce the error on a very simple transformation system:

- Create a type graph
- Create a node with a non-existent type that has an identifier, say x
- Use an expression referring to a field of that identified, but untyped node, say x.i

This crashes with the same stack trace, so I'm assuming it's the same bug

**Comment by rensink** [comment]
Once identified, it was easy to solve. Bug fix will appear in the next release!
